### ISSUE TITLE
Search Albums/Album View

### ISSUE THREAD

**Issue by MintMain21** [Insprill/intellectual#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I can search by song and by artist, and view pages dedicated to both. It would be nice to not only search albums, but to view albums as well. 

Specifically, I'd like to have all the songs on an album listed on the bottom of a song page similar to Genius.

**Comment by MintMain21** [comment]
A little more bare bones than I was expecting, as I can't search for albums and instead must search for songs from an album to find the album. 

Furthermore, there's no easy way to redirect Genius Album pages to Intellectual the same way I can redirect lyric pages or search results.

**Comment by Insprill** [comment]
Searching for albums will come a little later when searching for other things is added too. Not being able to easily redirect is a problem though, so I'll fix that.

**Comment by Insprill** [comment]
Sorry for the wait on this. Artists & albums are now based on path's instead of ID's as of b603617a32e4c278cfb59ea6398b340c4c38b2e4 and c96043cd92d5fe074a1d55df135d47dee09367d6. It's fairly robust regarding what path it can take, so redirecting should be fairly simple. The next release should be out by tomorrow evening (EST).
